import { FoodItem, UserProfile, DiaryEntry, Recommendation, SystemLog } from "../types.ts";

export const initialUsers: UserProfile[] = [
  {
    id: "usr-admin-1",
    name: "Alex Vance",
    email: "alex.vance@nutrigenius.ai",
    role: "ADMIN",
    token: "jwt-sim-token-admin-98a7c6f5",
    dailyCalorieGoal: 2200,
    waterGoalML: 3000,
    weightKG: 75,
    heightCM: 180,
    activityLevel: "Very Active",
    fitnessGoal: "Gain Muscle",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80"
  },
  {
    id: "usr-user-1",
    name: "Sarah Jenkins",
    email: "sarah.j@nutrigenius.ai",
    role: "USER",
    token: "jwt-sim-token-user-12b34c56",
    dailyCalorieGoal: 1800,
    waterGoalML: 2500,
    weightKG: 62,
    heightCM: 165,
    activityLevel: "Moderate",
    fitnessGoal: "Maintain Weight",
    avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80"
  }
];

export const initialFoods: FoodItem[] = [
  {
    id: "f-101",
    name: "Grilled Wild Alaskan Salmon",
    category: "Proteins & Meats",
    calories: 320,
    protein: 34.0,
    carbohydrates: 0.0,
    fat: 18.5,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 180,
    cholesterol: 85,
    vitamins: ["Vitamin D", "Vitamin B12", "Niacin"],
    minerals: ["Potassium", "Selenium", "Phosphorus"],
    ingredients: ["Wild Alaskan Salmon Fillet", "Sea Salt", "Cracked Black Pepper", "Lemon Juice", "Extra Virgin Olive Oil"],
    description: "Premium wild-caught salmon fillet rich in Omega-3 fatty acids and high-quality complete protein.",
    cuisine: "American",
    mealType: "Dinner",
    healthyRating: 5,
    views: 142,
    isFavorite: true,
    status: "Available",
    createdAt: "2026-07-20T10:00:00.000Z",
    updatedAt: "2026-07-25T14:30:00.000Z",
    barcode: "8901234500101",
    imageUrl: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80",
    allergens: ["Fish"],
    preparationTimeMinutes: 20,
    costPerServingUSD: 6.50,
    glycemicIndex: "Low",
    ecoScore: "A"
  },
  {
    id: "f-102",
    name: "Avocado Quinoa Power Salad",
    category: "Fruits & Vegetables",
    calories: 420,
    protein: 14.5,
    carbohydrates: 48.0,
    fat: 19.5,
    fiber: 9.2,
    sugar: 4.5,
    sodium: 320,
    cholesterol: 0,
    vitamins: ["Vitamin C", "Vitamin K", "Folate"],
    minerals: ["Iron", "Magnesium", "Zinc"],
    ingredients: ["Organic Quinoa", "Hass Avocado", "Cherry Tomatoes", "Baby Spinach", "Cucumber", "Lemon Vinaigrette"],
    description: "Nutrient-dense superfood salad packed with plant-based complete protein, healthy monounsaturated fats, and antioxidants.",
    cuisine: "Mediterranean",
    mealType: "Lunch",
    healthyRating: 5,
    views: 215,
    isFavorite: true,
    status: "Available",
    createdAt: "2026-07-21T11:15:00.000Z",
    updatedAt: "2026-07-26T09:20:00.000Z",
    barcode: "8901234500102",
    imageUrl: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80",
    allergens: ["None"],
    preparationTimeMinutes: 15,
    costPerServingUSD: 4.80,
    glycemicIndex: "Low",
    ecoScore: "A"
  },
  {
    id: "f-103",
    name: "Greek Yogurt Berry Parfait",
    category: "Dairy & Alternatives",
    calories: 280,
    protein: 22.0,
    carbohydrates: 34.0,
    fat: 4.5,
    fiber: 5.0,
    sugar: 18.0,
    sodium: 95,
    cholesterol: 15,
    vitamins: ["Vitamin B2", "Vitamin B12"],
    minerals: ["Calcium", "Phosphorus"],
    ingredients: ["0% Plain Greek Yogurt", "Organic Blueberries", "Strawberries", "Chia Seeds", "Raw Honey", "Almond Granola"],
    description: "High-protein probiotic snack layered with fresh antioxidant berries and crunchy chia granola.",
    cuisine: "European",
    mealType: "Breakfast",
    healthyRating: 5,
    views: 189,
    isFavorite: false,
    status: "Available",
    createdAt: "2026-07-22T08:30:00.000Z",
    updatedAt: "2026-07-26T16:45:00.000Z",
    barcode: "8901234500103",
    imageUrl: "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=600&q=80",
    allergens: ["Milk", "Tree Nuts"],
    preparationTimeMinutes: 5,
    costPerServingUSD: 3.20,
    glycemicIndex: "Medium",
    ecoScore: "A"
  },
  {
    id: "f-104",
    name: "Grass-Fed Beef Tenderloin Steak",
    category: "Proteins & Meats",
    calories: 450,
    protein: 42.0,
    carbohydrates: 0.0,
    fat: 30.0,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 410,
    cholesterol: 120,
    vitamins: ["Vitamin B6", "Vitamin B12", "Niacin"],
    minerals: ["Iron", "Zinc", "Phosphorus"],
    ingredients: ["Grass-Fed Tenderloin Steak", "Garlic Butter", "Rosemary", "Thyme", "Sea Salt"],
    description: "Prime grass-fed beef tenderloin seared with aromatic herb garlic butter. Outstanding source of bioavailable iron.",
    cuisine: "American",
    mealType: "Dinner",
    healthyRating: 4,
    views: 98,
    isFavorite: false,
    status: "Available",
    createdAt: "2026-07-18T18:00:00.000Z",
    updatedAt: "2026-07-24T12:00:00.000Z",
    barcode: "8901234500104",
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80",
    allergens: ["Milk"],
    preparationTimeMinutes: 25,
    costPerServingUSD: 12.00,
    glycemicIndex: "Low",
    ecoScore: "C"
  },
  {
    id: "f-105",
    name: "Matcha Green Tea Latte & Walnuts",
    category: "Snacks & Beverages",
    calories: 220,
    protein: 6.5,
    carbohydrates: 14.0,
    fat: 15.0,
    fiber: 3.0,
    sugar: 8.0,
    sodium: 65,
    cholesterol: 0,
    vitamins: ["Vitamin E", "Folate"],
    minerals: ["Magnesium", "Copper"],
    ingredients: ["Ceremonial Grade Matcha Powder", "Unsweetened Almond Milk", "Raw Walnuts", "Stevia Extract"],
    description: "Calm sustained focus from L-theanine combined with brain-healthy Omega-3 fatty acids from raw walnuts.",
    cuisine: "Japanese",
    mealType: "Snack",
    healthyRating: 5,
    views: 112,
    isFavorite: true,
    status: "Available",
    createdAt: "2026-07-23T15:00:00.000Z",
    updatedAt: "2026-07-26T18:00:00.000Z",
    barcode: "8901234500105",
    imageUrl: "https://images.unsplash.com/photo-1515823662972-da6a2e4d3002?auto=format&fit=crop&w=600&q=80",
    allergens: ["Tree Nuts"],
    preparationTimeMinutes: 5,
    costPerServingUSD: 2.50,
    glycemicIndex: "Low",
    ecoScore: "A"
  },
  {
    id: "f-106",
    name: "Double Cheeseburger with Bacon",
    category: "Fast Food & Cheats",
    calories: 820,
    protein: 46.0,
    carbohydrates: 44.0,
    fat: 52.0,
    fiber: 2.0,
    sugar: 9.0,
    sodium: 1450,
    cholesterol: 165,
    vitamins: ["Vitamin B12"],
    minerals: ["Iron", "Sodium"],
    ingredients: ["Brioche Bun", "Double Beef Patty", "Cheddar Cheese", "Smoked Bacon", "Special Sauce", "Pickles"],
    description: "Indulgent cheat meal with juicy double beef patties, melted cheddar cheese, and crispy bacon.",
    cuisine: "American",
    mealType: "Lunch",
    healthyRating: 1,
    views: 310,
    isFavorite: false,
    status: "Available",
    createdAt: "2026-07-15T13:00:00.000Z",
    updatedAt: "2026-07-22T10:00:00.000Z",
    barcode: "8901234500106",
    imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80",
    allergens: ["Wheat", "Milk", "Egg", "Soy"],
    preparationTimeMinutes: 15,
    costPerServingUSD: 8.50,
    glycemicIndex: "High",
    ecoScore: "D"
  },
  {
    id: "f-107",
    name: "Steamed Sweet Potato & Broccoli Bowl",
    category: "Fruits & Vegetables",
    calories: 340,
    protein: 9.0,
    carbohydrates: 72.0,
    fat: 3.0,
    fiber: 11.5,
    sugar: 14.0,
    sodium: 110,
    cholesterol: 0,
    vitamins: ["Vitamin A", "Vitamin C", "Vitamin K"],
    minerals: ["Potassium", "Manganese"],
    ingredients: ["Japanese Sweet Potato", "Organic Broccoli Florets", "Tahini Drizzle", "Sesame Seeds"],
    description: "Clean complex carbohydrate refueling bowl rich in beta-carotene and dietary fiber.",
    cuisine: "Asian",
    mealType: "Lunch",
    healthyRating: 5,
    views: 134,
    isFavorite: false,
    status: "Available",
    createdAt: "2026-07-19T12:00:00.000Z",
    updatedAt: "2026-07-25T11:00:00.000Z",
    barcode: "8901234500107",
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80",
    allergens: ["Sesame"],
    preparationTimeMinutes: 20,
    costPerServingUSD: 3.50,
    glycemicIndex: "Medium",
    ecoScore: "A"
  },
  {
    id: "f-108",
    name: "Classic Oatmeal with Sliced Banana",
    category: "Grains & Cereals",
    calories: 310,
    protein: 10.0,
    carbohydrates: 58.0,
    fat: 5.5,
    fiber: 8.0,
    sugar: 14.0,
    sodium: 45,
    cholesterol: 0,
    vitamins: ["Vitamin B1", "Vitamin B6"],
    minerals: ["Manganese", "Phosphorus", "Magnesium"],
    ingredients: ["Rolled Oats", "Ripe Banana", "Cinnamon", "Walnuts", "Almond Milk"],
    description: "Warm, heart-healthy whole grain breakfast rich in beta-glucan fiber to regulate cholesterol and blood sugar.",
    cuisine: "American",
    mealType: "Breakfast",
    healthyRating: 5,
    views: 175,
    isFavorite: true,
    status: "Available",
    createdAt: "2026-07-17T07:30:00.000Z",
    updatedAt: "2026-07-26T08:00:00.000Z",
    barcode: "8901234500108",
    imageUrl: "https://images.unsplash.com/photo-1517673132405-a56a62b18caf?auto=format&fit=crop&w=600&q=80",
    allergens: ["Tree Nuts"],
    preparationTimeMinutes: 10,
    costPerServingUSD: 1.80,
    glycemicIndex: "Medium",
    ecoScore: "A"
  }
];

export const initialDiary: DiaryEntry[] = [
  {
    id: "d-1",
    userId: "usr-user-1",
    foodId: "f-103",
    foodName: "Greek Yogurt Berry Parfait",
    mealType: "Breakfast",
    servings: 1,
    calories: 280,
    protein: 22.0,
    carbs: 34.0,
    fat: 4.5,
    date: new Date().toISOString().split('T')[0],
    timestamp: "08:30"
  },
  {
    id: "d-2",
    userId: "usr-user-1",
    foodId: "f-102",
    foodName: "Avocado Quinoa Power Salad",
    mealType: "Lunch",
    servings: 1,
    calories: 420,
    protein: 14.5,
    carbs: 48.0,
    fat: 19.5,
    date: new Date().toISOString().split('T')[0],
    timestamp: "12:45"
  },
  {
    id: "d-3",
    userId: "usr-user-1",
    foodId: "f-105",
    foodName: "Matcha Green Tea Latte & Walnuts",
    mealType: "Snack",
    servings: 1,
    calories: 220,
    protein: 6.5,
    carbs: 14.0,
    fat: 15.0,
    date: new Date().toISOString().split('T')[0],
    timestamp: "16:00"
  }
];

export const initialRecommendations: Recommendation[] = [
  {
    id: "rec-1",
    title: "High-Protein Recovery Snack",
    category: "Post-Workout",
    description: "Try pairing Greek yogurt with chia seeds and honey for a 25g protein boost within 30 minutes of resistance training.",
    matchScore: 98,
    calories: 280,
    tags: ["High-Protein", "Muscle Gain", "Quick Prep"]
  },
  {
    id: "rec-2",
    title: "Omega-3 Heart Shield Meal",
    category: "Dinner",
    description: "Grilled Wild Alaskan Salmon provides over 2,000mg of EPA/DHA Omega-3s to reduce inflammation and promote cardiovascular health.",
    matchScore: 95,
    calories: 320,
    tags: ["Heart Health", "Anti-Inflammatory", "Low-Carb"]
  },
  {
    id: "rec-3",
    title: "Sustained Energy Afternoon Bowl",
    category: "Lunch",
    description: "Avocado Quinoa Power Salad provides slow-digesting complex carbs and healthy fats to eliminate afternoon brain fog.",
    matchScore: 92,
    calories: 420,
    tags: ["High-Fiber", "Vegan", "Brain Health"]
  }
];

export const initialLogs: SystemLog[] = [
  {
    id: "log-1",
    timestamp: new Date().toLocaleTimeString(),
    user: "System",
    action: "BOOT",
    details: "NutriGenius AI Food & Nutrition DB engine initialized with MySQL & Spring Boot export readiness.",
    type: "INFO"
  },
  {
    id: "log-2",
    timestamp: new Date().toLocaleTimeString(),
    user: "Sarah Jenkins",
    action: "LOGIN",
    details: "User authenticated successfully in Standard mode.",
    type: "INFO"
  }
];
